version: '3.8'

services:
  firebytedb:
    image: mysql:latest
    container_name: firebytedb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fitebyteDB
      MYSQL_USER: firebyte
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

  firebytejava:
    image: openjdk:17.0.1-jdk-slim
    volumes:
      - ./app:/app
      - ./firebyte.jar:/app/firebyte.jar
    working_dir: /app
    depends_on:
      - firebytedb
    environment:
      DATABASE_URL: jdbc:mysql://firebytedb:3306/firebyteDB
      DATABASE_USER: firebyte
      DATABASE_PASSWORD: 1234
    stdin_open: true
    tty: true